### PR TITLE
Add `disconnect!` command (Resolves #98)

### LINKED ISSUE #98: connection_pool 2.1.2
I just upgraded to connection_pool 2.1.2 which adds an explicit disconnect to redis. 

Now redis-namespace is throwing deprecation warnings about blind passthrough. 

Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /opt/rubies/2.1.5/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block in discard!')

I saw in the code that indeed the command disconnect! for redis is missing could someone please fix this?

### PR DESCRIPTION
**Pull request by yaauie**
This should resolve #98. If someone has time to write a spec to verify it, I'd gladly accept it; otherwise I'll do it myself, merge & release this weekend.

### CODE REVIEW

**Comment by agrobbin** [comment]
It'd be great to get this merged soon. Our logs are overflowing with warnings about this.

**Comment by kjg** [comment]
Here is a spec that  might be acceptable. I'd love to see this PR get merged!

```diff
diff --git a/spec/redis_spec.rb b/spec/redis_spec.rb
index 0499518..94ffc91 100644
--- a/spec/redis_spec.rb
+++ b/spec/redis_spec.rb
@@ -337,6 +337,10 @@ describe "redis" do
     @namespaced.echo(123).should eq("123")
   end
 
+  it "should not add namespace to disonnect!" do
+    expect(@namespaced.disconnect!).to eq(nil)
+  end
+
   it "can change its namespace" do
     @namespaced['foo'].should eq(nil)
     @namespaced['foo'] = 'chris'
```

**Comment by foeken** [comment]
I can't find similar specs for commands like `auth` and `ping`. I believe a spec like @kjg suggested would be ok. Would you agree on that @yaauie? If so I can make a PR with both the change and the spec tomorrow for your approval.

**Comment by yaauie** [comment]
Hey, I'm sorry for the pain. `REDIS_NAMESPACE_QUIET` from the README is helpful for making redis-namespace be quiet.

I've added a spec that verifies it, and will put together a release as soon as Travis gets back to me with build status.

  it 'does not add a namespace to disconnect!' do
    expect(
  end

**Comment by foeken** [comment]
Awesome! Thank you very much ;)

**Comment by yaauie** [comment]
The build's passing, but it looks like I had some WIP on master that will likely add more noise. I've created a new branch called 1-x-stable based on the last release v1.5.1 that I'll backport this fix to.

**Comment by yaauie** [comment]
I've merged this into master, and have released 1.5.2 as 1.5.1 + this patch to rubygems.

**Pull request merged**
