### PR TITLE
Add support for `BITPOS` command

### PR DESCRIPTION
**Pull request by sponomarev**
hi!

[BITPOS](http://redis.io/commands/bitpos) command is totally safe and very useful to work with bitmaps

### CODE REVIEW

**Comment by sponomarev** [comment]
@yaauie what about merging this? :)

**Comment by shayne** [comment]
+1

**Comment by sponomarev** [comment]
Rebased over the latest master, tests were added. 

4,5 years passed ... I remember that as one of my earliest contributions on Github.  ❤️

**Comment by jeremy** [comment]
😅❤️

**Pull request merged**
