### PR TITLE
Port tests to RSpec3

### PR DESCRIPTION
**Pull request by balasankarc**

### CODE REVIEW

**Comment by yaauie** [comment]
Thanks! I'm in favor of bumping the `rspec` development dependency in the [gemspec](https://github.com/resque/redis-namespace/blob/master/redis-namespace.gemspec#L24), too; could you add that to your PR?

**Comment by balasankarc** [comment]
Sure. Will update the PR.

**Comment by balasankarc** [comment]
@yaauie Can you check why Travis CI fails? It succeeded in Ruby 1.8.7 and  1.9.2

**Comment by yaauie** [comment]
I've kicked the build; one failed because the CI server failed to bundle install, and the other failed because the CI failed to install rubinius.

**Comment by fw42** [comment]
CI should be fixed now. Can you rebase and try again?

**Comment by rafaelfranca** [comment]
Fixed in a different commit. Thank you so much.

**Pull request closed without merging**
